apiVersion: upbound.io/v1alpha1
kind: Builder
metadata:
  name: dynamodb-policy-example
spec:
  name: dynamodb-policy-example
  builderConfig:
    cloudParameters:
      iam:
        aws:
          region: us-west-2
          principal: torg-dynamodb-test1
          resourceArn: arn:aws:dynamodb:us-west-2:609897127049:table/torg-test-table1 # dynamodb table arn
          tags:
            key: iambuilder
            value: upbound
  compositionSelector:
    matchLabels:
      builder: iam
      cloud: aws
      service: dynamodb
      config: role-exists-crud # Change config to correct one
  resourceConfig:
    deletionPolicy: Delete
    providerConfigName: default
  