apiVersion: upbound.io/v1alpha1
kind: Builder
metadata:
  name: s3-bucket-policy-require-mfa-example
spec:
  name: s3-bucket-policy-require-mfa-example
  builderConfig:
    cloudParameters:
      iam:
        aws:
          region: us-west-2
          resourceArn: arn:aws:s3:::changeme-bucketname
  compositionSelector:
    matchLabels:
      builder: iam
      cloud: aws
      service: s3
      config: bucket-policy-require-mfa-example
  resourceConfig:
    providerConfigName: default