apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: builder
  annotations:
    meta.crossplane.io/maintainer: Aaron Torgerson <atorgerson@upbound.io>
    meta.crossplane.io/source: github.com/upbound/builder
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This builder configuration is used to standardize the building of supported services such as IAM on any cloud.

    meta.crossplane.io/readme: |
      This builder configuration is used to standardize the building of supported services such as IAM on any cloud. See the list of 
      compositions available for more detaiils.

spec:
  crossplane:
    version: ">=v1.7.0-0"