apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bucket-policy-require-mfa.s3.aws.iam.builder.upbound.io
  labels:
    builder: iam
    cloud: aws
    service: s3
    config: bucket-policy-require-mfa
  annotations:
    meta.upbound.io/builder-description: "Create a bucket policy to require multi-factor-auth"
    meta.upbound.io/builder-readme: "https://github.com/upbound/builder/tree/main/builders/aws#bucket-policy-require-mfa.s3.aws.iam.builder.upbound.io"
spec:
  compositeTypeRef:
    apiVersion: upbound.io/v1alpha1
    kind: XBuilder
  patchSets: []
  resources:
    - base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketPolicy
        spec:
          forProvider:
            policy: patched
      name: bucketPolicyRequireMFA
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.builderConfig.cloudParameters.iam.aws.resourceArn
            strategy: string
            string:
              fmt: |
               {
                  "Version": "2012-10-17",
                  "Id": "123",
                  "Statement": [
                    {
                      "Sid": "",
                      "Effect": "Deny",
                      "Principal": "*",
                      "Action": "s3:*",
                      "Resource": "%s",
                      "Condition": { "Null": { "aws:MultiFactorAuthAge": true }}
                    }
                  ]
                }
        - fromFieldPath: spec.builderConfig.cloudParameters.iam.aws.region
          toFieldPath: spec.forProvider.region
        - fromFieldPath: spec.name
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              fmt: "%s-require-mfa-rbp"
        - fromFieldPath: spec.name
          toFieldPath: spec.forProvider.bucket