apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bucket-policy-full-access.s3.aws.iam.builder.upbound.io
  labels:
    builder: iam
    cloud: aws
    service: s3
    config: bucket-policy-full-access
  annotations:
    meta.upbound.io/builder-description: "Create a full access bucket policy for all users"
    meta.upbound.io/builder-readme: "https://github.com/upbound/builder/tree/main/builders/aws#bucket-policy-full-access.s3.aws.iam.builder.upbound.io"
spec:
  compositeTypeRef:
    apiVersion: upbound.io/v1alpha1
    kind: XBuilder
  patchSets: []
  resources:
    - base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: BucketPolicy
        spec:
          forProvider:
            policy: patched
      name: bucketPolicyFullAccess
      patches:
        - fromFieldPath: spec.builderConfig.cloudParameters.iam.aws.resourceArn
          toFieldPath: spec.forProvider.policy
          transforms:
          - type: string
            string:
              fmt: |
                {
                  "Version": "2012-10-17",
                  "Statement": [{
                    "Sid": "FullAccess",
                    "Effect": "Allow",
                    "Principal": "*",
                    "Action": [
                      "s3:GetObject",
                      "s3:GetObjectAcl",
                      "s3:PutObject",
                      "s3:PutObjectAcl",
                      "s3:DeleteObject",
                      "s3:DeleteObjectTagging",
                      "s3:DeleteObjectVersionTagging",
                      "s3:GetObjectTagging",
                      "s3:GetObjectVersionTagging",
                      "s3:PutObjectTagging",
                      "s3:PutObjectVersionTagging"
                    ],
                    "Resource": [
                      "%s/*"
                    ]
                  }]
                } 
        - fromFieldPath: spec.builderConfig.cloudParameters.iam.aws.region
          toFieldPath: spec.forProvider.region
        - fromFieldPath: spec.name
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              fmt: "%s-full-access-rbp"
        - fromFieldPath: spec.name
          toFieldPath: spec.forProvider.bucket