apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: group-crud.s3.aws.iam.builder.upbound.io
  labels:
    builder: iam
    cloud: aws
    service: s3
    config: group-crud
  annotations:
    meta.upbound.io/builder-description: "Create crud policy for a bucket and assign it to a group"
    meta.upbound.io/builder-readme: "https://github.com/upbound/builder/tree/main/builders/aws#group-crud.s3.aws.iam.builder.upbound.io"
spec:
  compositeTypeRef:
    apiVersion: upbound.io/v1alpha1
    kind: XBuilder
  patchSets:
    - name: common-fields
      patches:
        - fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - fromFieldPath: spec.builderConfig.cloudParameters.iam.aws.tags
          toFieldPath: spec.forProvider.tags
  resources:
    - base:
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: Policy
        spec:
          forProvider:
            description: "Policy for s3 bucket CRUD"
            policy: patched
      name: s3CrudPolicy
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - fromFieldPath: spec.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-s3-crud"
        - type: CombineFromComposite
          toFieldPath: spec.forProvider.policy
          combine:
            variables:
              - fromFieldPath: spec.builderConfig.cloudParameters.iam.aws.resourceArn
              - fromFieldPath: spec.builderConfig.cloudParameters.iam.aws.resourceArn
            strategy: string
            string:
              fmt: |
                  {
                    "Version": "2012-10-17",
                    "Statement": [
                      {
                        "Effect": "Allow",
                        "Action": "s3:ListAllMyBuckets",
                        "Resource": "*"
                      },
                      {
                        "Effect":"Allow",
                        "Action":["s3:ListBucket","s3:GetBucketLocation"],
                        "Resource":"%s"
                      },
                      {
                        "Effect": "Allow",
                        "Action": [
                           "s3:PutObject",
                           "s3:GetObject",
                           "s3:DeleteObject"
                        ],
                        "Resource": "%s/*"
                      }
                    ]
                  }
    - base:
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: GroupPolicyAttachment
      name: s3GroupPolicyAttachment
      patches:
        - fromFieldPath: spec.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-s3-gpa"
        - fromFieldPath: spec.builderConfig.cloudParameters.iam.aws.principal
          toFieldPath: spec.forProvider.group
        - fromFieldPath: spec.name
          toFieldPath: spec.forProvider.policyArnRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-s3-crud"
